'use client'
import './globals.css'
import { Poppins } from 'next/font/google'
import Navigation from './Components/Navigation'
import { configureStore } from "@reduxjs/toolkit";
import { Provider } from "react-redux";
import coinSlice, { changeCoin } from "./Slices/coinSlice";

const poppins = Poppins({
   subsets: ['latin'],
   weight: ['300', '400', '700']
  
  })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const store = configureStore({
  reducer: {
    coin: coinSlice
  }
 } )

 function ReduxProvider({children}) {
  return <Provider store={store}>{children}</Provider>
 }

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body  className={`${poppins.className} bg-Purps text-2xl text-white overflow-x-hidden`}>
      <Navigation />
      <ReduxProvider store={store}>

        {children}
      </ReduxProvider>
        
        </body>
    </html>
   
  )
}
